# Generated by Django 6.0.1 on 2026-01-14 02:36

import apps.user.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[apps.user.models.validators.validate_email_format],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(
                max_length=10,
                unique=True,
                validators=[apps.user.models.validators.validate_nickname_format],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=20,
                validators=[apps.user.models.validators.validate_phone_format],
            ),
        ),
    ]
