# Generated by Django 6.0.1 on 2026-01-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("M", "MALE"), ("F", "FEMALE")], default="M", max_length=1
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
    ]
