# Generated by Django 6.0.1 on 2026-01-12 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="withdrawal",
            name="user",
        ),
        migrations.DeleteModel(
            name="User",
        ),
        migrations.DeleteModel(
            name="Withdrawal",
        ),
    ]
