# Generated by Django 6.0.1 on 2026-01-16 08:17

import apps.user.validators.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_name_alter_user_email_alter_user_nickname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(
                max_length=100,
                unique=True,
                validators=[apps.user.validators.validate_email_format],
            ),
        ),
    ]
