# Generated by Django 6.0.1 on 2026-01-12 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="preference",
            old_name="is_deleted_at",
            new_name="deleted_at",
        ),
    ]
