# Generated by Django 6.0.1 on 2026-01-19 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_email"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Preference",
        ),
    ]
