# Generated by Django 6.0.1 on 2026-01-27 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("preference", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="preference",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="category",
            field=models.ForeignKey(
                db_column="category_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="preference.tagcategory",
            ),
        ),
        migrations.AddConstraint(
            model_name="preference",
            constraint=models.UniqueConstraint(
                fields=("user", "genre"), name="unique_user_preference"
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                fields=("category", "name"), name="unique_category_tag"
            ),
        ),
    ]
