# Generated by Django 6.0.1 on 2026-01-27 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("game", "0001_initial"),
        ("preference", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="genrepreference",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tagpreference",
            name="tag",
            field=models.ForeignKey(
                db_column="tag_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preferred_users",
                to="game.tag",
            ),
        ),
        migrations.AddField(
            model_name="tagpreference",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_tags",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="genrepreference",
            constraint=models.UniqueConstraint(
                fields=("user", "genre"), name="unique_user_preference"
            ),
        ),
        migrations.AddConstraint(
            model_name="tagpreference",
            constraint=models.UniqueConstraint(
                fields=("user", "tag"), name="unique_user_tag_preference"
            ),
        ),
    ]
