# Generated by Django 6.0.2 on 2026-02-05 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("preference", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TagCategory",
        ),
    ]
