# Generated by Django 6.0.1 on 2026-01-19 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
        ("game", "0002_genre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamereviewsummary",
            name="is_deleted",
        ),
        migrations.AddField(
            model_name="gamereviewsummary",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="gamereviewsummary",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="gamereviewsummary",
            name="game",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="summary",
                to="game.game",
            ),
        ),
    ]
