# Generated by Django 6.0.1 on 2026-01-27 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0002_usertendency"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="usertendency",
            table="user_tendency",
        ),
    ]
