# Generated by Django 6.0.2 on 2026-02-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0003_alter_usertendency_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertendency",
            name="tendency",
            field=models.CharField(
                blank=True,
                help_text="AI가 분석한 10자 이내의 게이머 성향",
                max_length=20,
                null=True,
            ),
        ),
    ]
