# Generated by Django 6.0.1 on 2026-01-13 02:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("game", "0002_genre"),
        ("user", "0004_rename_is_deleted_at_preference_deleted_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField(verbose_name="리뷰 내용")),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        help_text="1~5 사이의 정수",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="별점",
                    ),
                ),
                (
                    "view_count",
                    models.BigIntegerField(default=0, verbose_name="조회수"),
                ),
                (
                    "like_count",
                    models.BigIntegerField(default=0, verbose_name="좋아요 합계"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="삭제 여부"),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="game.game",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="user.user",
                    ),
                ),
            ],
            options={
                "db_table": "reviews",
                "indexes": [
                    models.Index(
                        fields=["game", "-like_count"], name="idx_reviews_best"
                    )
                ],
            },
        ),
    ]
