# Generated by Django 6.0.1 on 2026-01-16 08:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0003_reviewlike"),
        ("game", "0002_genre"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="review",
            name="idx_reviews_best",
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["game"], name="idx_reviews_best"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["like_count"], name="idx_reviews_best_like_count"
            ),
        ),
    ]
