# Generated by Django 6.0.1 on 2026-01-21 01:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0004_remove_review_idx_reviews_best_and_more"),
        ("game", "0003_delete_genre"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="review",
            name="idx_reviews_best",
        ),
        migrations.RemoveIndex(
            model_name="review",
            name="idx_reviews_best_like_count",
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["game", "like_count"], name="idx_reviews_game_best"
            ),
        ),
    ]
