# Generated by Django 6.0.1 on 2026-01-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("intro", models.TextField()),
                ("released_at", models.DateTimeField()),
                ("developer", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("id_deleted", models.BooleanField(default=False)),
                ("avg_score", models.FloatField(default=0)),
            ],
            options={
                "db_table": "games",
            },
        ),
    ]
