# Generated by Django 6.0.1 on 2026-01-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="genre",
            name="genre_ko",
            field=models.CharField(default="steam", max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tag",
            name="tag_ko",
            field=models.CharField(default="steam", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
