# Generated by Django 6.0.1 on 2026-01-19 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_genre"),
        ("user", "0004_delete_preference"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Genre",
        ),
    ]
