# Generated by Django 6.0.1 on 2026-01-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_delete_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='publisher',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='released_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
