# Generated by Django 6.0.1 on 2026-01-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_delete_genre"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Genre", models.CharField(max_length=255)),
                ("Genre_ko", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "genre",
            },
        ),
    ]
