# Generated by Django 6.0.1 on 2026-02-02 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_remove_game_avg_score_wishlist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="id_deleted",
            new_name="is_deleted",
        ),
    ]
