# Generated by Django 6.0.1 on 2026-01-27 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_publisher_alter_game_released_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('genre_ko', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='GameGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_genres', to='game.game')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_genres', to='game.genre')),
            ],
            options={
                'db_table': 'game_genres',
                'unique_together': {('game', 'genre')},
            },
        ),
    ]
