# Generated by Django 6.0.1 on 2026-01-27 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_platform_tag_remove_genre_genre_ko_gameplatform_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameImg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img_url", models.TextField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_images",
                        to="game.game",
                    ),
                ),
            ],
            options={
                "db_table": "game_img",
            },
        ),
    ]
